ktor:
    application:
        modules:
            - com.paling.ApplicationKt.module
    deployment:
        host: "localhost" # set to localhost so that copy to clipboard is enabled
        port: "8080"
